name: 3DS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install devkitPro pacman (devkitARM + tools)
        run: |
          sudo apt update
          sudo apt install -y devkitpro-pacman
          sudo dkp-pacman -Sy --noconfirm devkitARM general-tools 3ds-dev

      - name: Build project
        run: |
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 3ds-build
          path: |
            *.3dsx
            *.cia
            romfs/*
