name: 3DS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # Install devkitPro
      - name: Setup devkitPro
        run: |
          sudo apt update
          sudo apt install -y devkitpro-pacman
          sudo dkp-pacman -Sy --noconfirm devkitARM general-tools 3ds-dev

      # Build project
      - name: Build 3DS project
        run: |
          make

      # Upload artifacts (.3dsx, .cia, etc.)
      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: 3ds-build
          path: |
            *.3dsx
            *.cia
            romfs/*
